travis:
  secure:
    BINSTAR_TOKEN: RmpXH4cYCn/Slkrh9ouXiPL4GBKw+VVK1kEt4le7UN96NzfUJzCGgRNSIzoG2WbwJKiL4Ish56Pwj/ceNq/49Zdtg8k6fw9MijK9W4G/gL8CsdJoeEPXoyiPzZGKDYJ0jMevqKL5YC6QhyQ3QTbjI4YOOANp+d8w1ElFn6q6RDLd7P5W/Ppde0wJwqgJEkaZGSWZjrEhLWgTWJJxmUtstoKLC22qxSroMsTZfiN4IwXpLIr0sUY3dtRupCega6Rd3ete+aD7hKkb734CZE2cejMm/SrAu9Ssf3Osk/KAIuOwadWdv4KSRwRoGPAv/dyP5v4Ukx4pu+H62/S2BMaffTwDmgOsewQFxDGDUcZOHEwrmjyF+ZTdRRd3nDjn0m0A03GZ51FsOZI/R/QwagH3aifXYLK9DFzs7TVFhhuPSbpIncATE4sDaw93hAO5KaRuBG4g8cprXGbDuGIdKCJj0CK01cUEoff4uXR17Ws99H6NqluAYPlLb21l6UAVn6AKjMKF2jyOu1btgLDqvqmB6lrzBicryUAPjx8iumH/wwppnfra90TFvc3WMoI3jRE9PNC2V56+ZCxqjKnWMJFwNZrCGmZWCbm5SOwywxdKVqs+dt412GyxClmM1KmrlrJmRQGhlrVKv0jIJDXVZvqV3YXkmjg6/zcwiwoI/WV0bx8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
