travis:
  secure:
    BINSTAR_TOKEN: vpIPMrtAjSTgd2LFU0xLoYgE/xkB3oF/eEOavDtuImLlO7Ks+1SQ2HsW9j1D0xz8sHez6pu+EvytkFzBIqM8QjR4Jfu+plGe0ZtapAC1kvfEKBYxGVMSw1PAQtMJmUitt8lVIDMBU2zAQDdJD1LPs+F9VB8iQmMV1EfSoX5Hslk66tyzatQn9oKNBW4uzTFhTRrHsgaiwNqx9IWKq1THaB/nC16jhWwBmX3PN03C9yQb+j/JTQtPhvnGjIgnx8/rkPtA94NGqG4Tfw5TD9NWaS3Wb4s2wHz01uJUHQliiAi0oMouVGMWZ5NN8WsirmOlh7KCJ2GpIHt6XdOjnh0bGzXzcSbGud/tjYz7MUaHwZpWVqn/oZ+U4RV4d8iy3jFRQzX+Vipn+pIy+he9FctcwBwm3krLqq7Ju27+OO/WSCMp8x5PkIo7/kaGECHWdrvl1z3V0V3sKiqCbtPmhFglRx5pemzRYWek215tne/k14ej+9PCV55HnS3pocfnutnus2ph2Zm8ZmBdva2RNt6CRieBbrhCZJpe0Sn6NxnRPWtYjB6h4g66FnB/EtefL3EhdUJEnieAtaExWrcW2uJzrtqTSlm2x+nGYiwp2Oh9Ei9Yfd42Qy4xnlFX6+UcTMgwI40rDcUQUeSF1F9AYitEVknrIbVSPS836W7TW2o15VI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
